# Generated by Django 6.1.1 on 2026-09-28 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=250)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_total', models.PositiveIntegerField()),
                ('stock_disponible', models.PositiveIntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_entrada', to='eventos.evento')),
            ],
            options={
                'verbose_name': 'tipo de entrada',
                'verbose_name_plural': 'tipos de entrada',
                'ordering': ('evento', 'precio'),
                'constraints': [models.UniqueConstraint(fields=('evento', 'nombre'), name='tipo_entrada_nombre_unico_por_evento')],
            },
        ),
    ]
