# Generated by Django 6.1.1 on 2026-10-03 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_evento_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='modalidad_entrada',
            field=models.CharField(choices=[('GENERAL', 'Entrada general / libre'), ('UBICACION', 'Entrada con ubicacion')], default='GENERAL', max_length=20),
        ),
        migrations.CreateModel(
            name='Locacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=250)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locaciones', to='eventos.evento')),
            ],
            options={
                'verbose_name': 'locacion',
                'verbose_name_plural': 'locaciones',
                'ordering': ('evento', 'orden', 'nombre'),
            },
        ),
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('fila', models.CharField(blank=True, max_length=10)),
                ('numero', models.PositiveIntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('locacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asientos', to='eventos.locacion')),
            ],
            options={
                'verbose_name': 'asiento',
                'verbose_name_plural': 'asientos',
                'ordering': ('locacion', 'fila', 'numero', 'codigo'),
            },
        ),
        migrations.AddConstraint(
            model_name='locacion',
            constraint=models.UniqueConstraint(fields=('evento', 'nombre'), name='locacion_nombre_unico_por_evento'),
        ),
        migrations.AddConstraint(
            model_name='asiento',
            constraint=models.UniqueConstraint(fields=('locacion', 'codigo'), name='asiento_codigo_unico_por_locacion'),
        ),
    ]
