# Generated by Django 6.1.1 on 2026-10-03 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_evento_modalidad_entrada_locacion_asiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locacion',
            name='tipo_entrada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locaciones', to='eventos.tipoentrada'),
        ),
    ]
