# Generated by Django 6.1.1 on 2026-10-03 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_locacion_tipo_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='tipo_escenario',
            field=models.CharField(choices=[('FRONTAL_SIMPLE', 'Frontal simple'), ('FRONTAL_TRIBUNAS', 'Frontal con tribunas'), ('CENTRAL', 'Central'), ('SIN_ESCENARIO', 'Sin escenario')], default='FRONTAL_SIMPLE', max_length=30),
        ),
    ]
