# Generated by Django 6.1.1 on 2026-10-03 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_evento_tipo_escenario'),
    ]

    operations = [
        migrations.AddField(
            model_name='locacion',
            name='posicion',
            field=models.CharField(choices=[('FRONTAL', 'Frontal'), ('IZQUIERDA', 'Lateral izquierda'), ('DERECHA', 'Lateral derecha'), ('ALREDEDOR', 'Alrededor / central')], default='FRONTAL', max_length=20),
        ),
    ]
