# Generated by Django 6.1.1 on 2026-10-04 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_locacion_posicion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locacion',
            name='posicion',
            field=models.CharField(choices=[('FRONTAL', 'Frontal'), ('POSTERIOR', 'Posterior'), ('IZQUIERDA', 'Lateral izquierda'), ('DERECHA', 'Lateral derecha'), ('LIBRE', 'Libre')], default='FRONTAL', max_length=20),
        ),
    ]
