# Generated by Django 6.1.1 on 2026-10-04 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0008_alter_locacion_posicion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='tipo_escenario',
            field=models.CharField(choices=[('FRONTAL_SIMPLE', 'Frontal simple'), ('FRONTAL_TRIBUNAS', 'Frontal con tribunas'), ('CENTRAL', 'Central'), ('LIBRE', 'Escenario frontal + zona libre')], default='FRONTAL_SIMPLE', max_length=30),
        ),
    ]
