# Generated by Django 6.1.1 on 2026-10-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0002_itemcarrito_asiento'),
        ('eventos', '0005_locacion_tipo_entrada'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='itemcarrito',
            name='item_unico_tipo_entrada_por_carrito',
        ),
        migrations.AddConstraint(
            model_name='itemcarrito',
            constraint=models.UniqueConstraint(condition=models.Q(('asiento__isnull', True)), fields=('carrito', 'tipo_entrada'), name='item_general_unico_por_carrito'),
        ),
        migrations.AddConstraint(
            model_name='itemcarrito',
            constraint=models.UniqueConstraint(condition=models.Q(('asiento__isnull', False)), fields=('carrito', 'asiento'), name='asiento_unico_por_carrito'),
        ),
    ]
