# Generated by Django 6.1.1 on 2026-09-28 22:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('estado', models.CharField(choices=[('VALIDA', 'Válida'), ('UTILIZADA', 'Utilizada'), ('ANULADA', 'Anulada')], default='VALIDA', max_length=20)),
                ('emitida_en', models.DateTimeField(auto_now_add=True)),
                ('utilizada_en', models.DateTimeField(blank=True, null=True)),
                ('detalle_compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='compras.detallecompra')),
            ],
            options={
                'verbose_name': 'entrada',
                'verbose_name_plural': 'entradas',
                'ordering': ('-emitida_en',),
            },
        ),
    ]
