# Generated by Django 6.1.1 on 2026-10-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='oculta_usuario',
            field=models.BooleanField(default=False),
        ),
    ]
