# Generated by Django 6.1.1 on 2026-10-03 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
        ('eventos', '0005_locacion_tipo_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompra',
            name='asiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_compra', to='eventos.asiento'),
        ),
    ]
