# Generated by Django 6.1.1 on 2026-10-10 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_detallecompra_asiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='oculta_en_historial',
            field=models.BooleanField(default=False, help_text='Oculta la compra del historial visible del usuario.'),
        ),
    ]
