# Generated by Django 6.1.1 on 2026-10-10 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_compra_oculta_en_historial'),
        ('eventos', '0009_alter_evento_tipo_escenario'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='detallecompra',
            name='detalle_unico_tipo_entrada_por_compra',
        ),
        migrations.AddConstraint(
            model_name='detallecompra',
            constraint=models.UniqueConstraint(condition=models.Q(('asiento__isnull', True)), fields=('compra', 'tipo_entrada'), name='detalle_general_unico_por_compra'),
        ),
        migrations.AddConstraint(
            model_name='detallecompra',
            constraint=models.UniqueConstraint(condition=models.Q(('asiento__isnull', False)), fields=('compra', 'asiento'), name='detalle_asiento_unico_por_compra'),
        ),
    ]
